Remove go link from README.md
google/new-project pull request #50
Opened 2023-05-27 00:58 UTC by billnapier

autocross flags go links as a "potential" issue, meaning you always need  to make further changes to get cross to pass your launch, if you base your repository off this template.

2023-05-27 01:00 UTC, billnapier commented
My hopes with this change is to reduce the amount of toil work when launching an empty repository.  In theory you can just import this repository to a new empty repository (easily done from the github UI) and then have something that immediately passes cross.  You should then go fix the readme pretty quickly after since it doesn't make sense, but at least one less step to get your release approved.

2023-05-30 23:18 UTC, rspier commented
> You should then go fix the readme pretty quickly after since it doesn't make sense, but at least one less step to get your release approved.

Wouldn't it be better for someone to update the README before running cross?  I kind of like the friction here.

Alternatively, why not tell cross that some go links are ok?   http://shortn/_J2pamO4bw3 has a list from a few years ago.

2023-05-30 23:18 UTC, rspier requested changes

2023-05-30 23:18 UTC, rspier commented on README.md
> +See [Go Releasing](https://opensource.google/documentation/reference/releasing)
The opensource.google copy is a few years out of date.  We shouldn't be pointing Googlers at it.

2023-11-18 17:50 UTC, closed without merging